# Generated by Django 5.0.2 on 2025-04-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название последовательности')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активная')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Последовательность',
                'verbose_name_plural': 'Последовательности',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Число')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='randomizer.sequence', verbose_name='Последовательность')),
            ],
            options={
                'verbose_name': 'Число',
                'verbose_name_plural': 'Числа',
                'ordering': ['position'],
            },
        ),
    ]
